[package]
name = "rust-guessing-game"
version = "0.1.0"
edition = "2021"
authors = ["João Paulo de Faveri <joao.faveri@gmail.com>"]
rust-version = "1.63.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]